# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PacketlyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'IQKeyboardManagerSwift'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'Alamofire', '~> 5.4'
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'Toast-Swift'

  # Pods for PacketlyApp

end
